del sekcije/*.aux
del seminarski.aux
del seminarski.log
del seminarski.out
del seminarski.synctex.gz
del seminarski.toc
del seminarski.blg
del seminarski.bbl
del 10_recenzije.aux
del 10_recenzije.log
del 10_recenzije.out
del 10_recenzije.synctex.gz
del 10_recenzije.toc